---
- name: Clone the repository
  become: true
  git:
    repo: "https://github.com/alibaba0010/hng12-DevOps-Stage-4.git"
    dest: /home/ubuntu/todo-app
    version: main
    force: yes

- name: Set correct permissions for acme.json
  become: true
  file:
    path: /home/ubuntu/todo-app/letsencrypt/acme.json
    state: touch
    mode: "0600"

# Uncomment and adjust this task if needed
- name: Setup SSL cert
  become: true
  shell: |
    curl "https://www.duckdns.org/update?domains=adedibu.duckdns.org&token=80cf7b89-2f2a-4ab5-80a1-c800e889dfc4&ip={{ ansible_host }}"

- name: Check if docker network exists
  become: true
  command: docker network ls --filter name=app-network --format "{{'{{.Name}}'}}"
  register: network_check
  changed_when: false

- name: Create docker network if not exists
  become: true
  command: docker network create app-network
  when: network_check.stdout == ""

- name: Run Docker Compose
  become: true
  command:
    cmd: docker compose up -d
    chdir: /home/ubuntu/todo-app
